apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi
  namespace: mlr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
      - name: restapi
        image: rest-soap-kubernetes-rest-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: restapi-service
  namespace: mlr-api
spec:
  selector:
    app: restapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort
