apiVersion: apps/v1
kind: Deployment
metadata:
  name: soapapi
  namespace: mlr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soapapi
  template:
    metadata:
      labels:
        app: soapapi
    spec:
      containers:
      - name: soapapi
        image: rest-soap-kubernetes-soap-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: soapapi-service
  namespace: mlr-api
spec:
  selector:
    app: soapapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  type: ClusterIP
