version: '3.8'
services:
  api_rest_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TheBestPassword
      POSTGRES_DB: restaurantDB
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: restaurantDB

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    container_name: redis

  api_rest:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api_rest_db
      - redis
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - host=api_rest_db
      - port=5432
      - name=restaurantDB
      - pass=TheBestPassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    container_name: API_Restaurant

volumes:
  postgres_data:
